# Dockerfile has been added in all micro-services, you need to dockerize all micro-services and add docker-compose.yml file
version: '3'
services:
  user-auth:
    image: user-auth
    build:
      context: UserAuthentication-Service/
    restart: always
    ports:
      - 8089:8089
    links:
      - user-mysql

  reminder-service:
    image: reminder-app
    build:
      context: ReminderService/
    restart: always
    ports:
        - 8081:8081
    links:
        - mongo-service

  note-service:
    image: note-app
    build:
      context: NoteService/
    restart: always
    ports:
      - 8082:8082
    links:
      - mongo-service

  category-service:
     image: category-app
     build:
       context: CategoryService/
     restart: always
     ports:
       - 8083:8083
     links:
       - mongo-service

  user-service:
     image: user-app
     build:
       context: UserService/
     restart: always
     ports:
       - 8080:8080
     links:
       - mongo-service

  user-mysql:
    image: mysql:5.6
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_USER: app-root
      MYSQL_PASSWORD: root123
      MYSQL_DATABASE: userDb

  mongo-service:
      image: mongo:latest
      command: mongod --port 27018
      restart: always
      ports:
        - 27017:27018